### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by chrishiestand** [aladdin-add/eslint-plugin-no-autofix#3]
Just tried the plugin and can't get it working. Here's my `.eslintrc.yml`:

```yaml
extends:
- react-app
- airbnb
- prettier

plugins:
- prettier
- no-autofix

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  strict:
  - "error"
  - "global"
  no-unused-vars:
  - error
  - argsIgnorePattern: "^_"
    varsIgnorePattern: "^_"
  react/jsx-filename-extension:
  - error,
  - extensions:
    - .js
    - .jsx
  react/jsx-one-expression-per-line:
  - error,
  - allow: "single-child"
  prettier/prettier:
    - error
    -
      trailingComma: all
      bracketSpacing: false
  no-autofix/prefer-const: error
```

When I type

```javascript
let a = "foo";
```

it is "fixed" to:

```javascript
const a = "foo";
```

I expect to still have `let` but with a linter error.
